import { motion } from "framer-motion";
import { FileText, CheckCircle2, AlertTriangle } from "lucide-react";

export default function TermsPage() {
    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="max-w-4xl mx-auto space-y-8 p-4 md:p-8"
        >
            <div className="space-y-4">
                <h1 className="text-3xl md:text-4xl font-black text-white tracking-tight">Terms of Service</h1>
                <p className="text-[#8696a0] text-lg">Effective Date: {new Date().toLocaleDateString()}</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
                <div className="bg-[#182630]/50 border border-[#202c33] rounded-2xl p-6 flex items-start space-x-4">
                    <div className="w-10 h-10 rounded-full bg-[#00a884]/20 flex shrink-0 items-center justify-center">
                        <CheckCircle2 size={20} className="text-[#00a884]" />
                    </div>
                    <div>
                        <h3 className="text-white font-bold text-lg">Your Responsibilities</h3>
                        <p className="text-[#8696a0] text-sm mt-2">You agree to only upload chat datasets that belong to you or that you have explicit permission to access and analyze.</p>
                    </div>
                </div>
                <div className="bg-[#182630]/50 border border-[#202c33] rounded-2xl p-6 flex items-start space-x-4">
                    <div className="w-10 h-10 rounded-full bg-[#ef4444]/20 flex shrink-0 items-center justify-center">
                        <AlertTriangle size={20} className="text-[#ef4444]" />
                    </div>
                    <div>
                        <h3 className="text-white font-bold text-lg">Code of Conduct</h3>
                        <p className="text-[#8696a0] text-sm mt-2">Do not exploit ChatScope to analyze illegally obtained data or engage in abusive, malicious scraping behavior.</p>
                    </div>
                </div>
            </div>

            <div className="space-y-6 text-[#e9edef] bg-[#111b21] p-8 rounded-2xl border border-[#202c33]">
                <section className="space-y-3">
                    <div className="flex items-center gap-3">
                        <FileText size={20} className="text-[#00a884]" />
                        <h2 className="text-xl font-bold">1. Agreement to Terms</h2>
                    </div>
                    <p className="text-[#8696a0] leading-relaxed">
                        By using ChatScope, you are agreeing to these terms. Please read them carefully. We reserve the right to suspend or terminate services temporarily or permanently for users violating these terms.
                    </p>
                </section>

                <section className="space-y-3">
                    <div className="flex items-center gap-3">
                        <FileText size={20} className="text-[#00a884]" />
                        <h2 className="text-xl font-bold">2. Service Modifications</h2>
                    </div>
                    <p className="text-[#8696a0] leading-relaxed">
                        ChatScope is provided primarily as an analytics and visualization utility. We reserve the right to adjust computational limits, file size restrictions, or feature availability to ensure platform stability and prevent abuse.
                    </p>
                </section>

                <section className="space-y-3">
                    <div className="flex items-center gap-3">
                        <FileText size={20} className="text-[#00a884]" />
                        <h2 className="text-xl font-bold">3. Warranties & Disclaimers</h2>
                    </div>
                    <p className="text-[#8696a0] leading-relaxed">
                        The metrics, patterns, and insights provided by ChatScope—especially those generated by AI features—are offered "as is" and without warranties. AI analysis may contain inaccuracies. Users should rely on their own judgment regarding decisions strictly based on these analytics.
                    </p>
                </section>

                <section className="space-y-3">
                    <div className="flex items-center gap-3">
                        <FileText size={20} className="text-[#00a884]" />
                        <h2 className="text-xl font-bold">4. User Uploaded Content</h2>
                    </div>
                    <p className="text-[#8696a0] leading-relaxed">
                        You retain full ownership and intellectual property rights to any export files you provide. ChatScope claims no rights to your chat history, but requires the license to temporarily parse it in memory to deliver the requested analytics. Once your session clears, the transaction concludes entirely.
                    </p>
                </section>
            </div>
        </motion.div>
    );
}
